
# RUN dnf install nginx -y
# CMD ["nginx", "-g", "daemon off;"]
# LABEL author="Goutham Rohan" \
#       course="Devops" \
#       topic="Docker" \  
# EXPOSE 80/tcp

FROM almalinux:9
ENV trainer="GouthamRohan" \
    course="docker" \
    duration="100hr" 
CMD ["sleep", "100"]    